### ISSUE TITLE
create edit study feature

### ISSUE THREAD

**Issue by andreamoreno-cs** [2E-arly/emerald-code-sparks#28]
### Tasks: 

- [x] add edit study button to create study page (done)
- [x] Create form for researchers to update their study name and description (done)
- [x] When button clicked - modal opens allowing researchers to easily edit.  (done)
- [x] Update study object on strapi (handle PUT requests) (done)

Completion Status: done

- Acceptance Criteria: As a researcher, I want to be able to edit my study name and description easily. 
- Testing: Manual Testing with interaction with browser for UI testing, browser console for errors and warnings, form validation for form submission and handling. Static testing with sonar cloud.

### Progress

- [x] Edit button
- [x] Create form/modal
- [x] Implement hooks
- [x] Create request
- [x] Test

[Wireframe](https://www.figma.com/file/gr6Kq308N8PAP357dgv8tI/2e-Wireframe?type=design&node-id=0-1&mode=design&t=6crp83psXQTcoDKn-0)
